services:
  app:
    image: img-redis-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  redis-data:
    driver: local